blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/koncord/bis-toolkit/blob/main/README.md
    about: Read the documentation for usage and setup instructions
